const ChatActionTypes = {
    FIND_PAIR_START: 'FIND_PAIR_START',
    FIND_PAIR_SUCCESS: 'FIND_PAIR_SUCCESS',
    PAIR_DISCONNECTED: 'PAIR_DISCONNECTED',
    APPEND_MESSAGE: 'APPEND_MESSAGE',
    SEND_MESSAGE: 'SEND_MESSAGE',
    LEAVE_ROOM: 'LEAVE_ROOM'
};

export default ChatActionTypes;